version: '3'
services: 
    frontend-web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "5000:5000"
        volumes: 
            - /app/node_modules
            - .:/app