version: '3'
services: 
    frontend-web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "8000:8000"
        volumes: 
            - /app/node_modules
            - .:/app