sudo: required
services:
  - docker

before_install:
  - docker build -t haivx/frontend:latest -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t xuanhai/muti-client ./client
  - docker build -t xuanhai/muti-server ./server
  - docker build -t xuanhai/muti-nginx ./nginx