sudo: required
services:
  - docker

before_install:
  - docker build -t haivx/frontend:latest -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true xuanhai/react-test npm test

after_success:
  - docker build -t xuanhai/muti-client ./frontend
  - docker build -t xuanhai/muti-server ./server
  - docker build -t xuanhai/muti-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push xuanhai/muti-client
  - docker push xuanhai/muti-server
  - docker push xuanhai/muti-nginx