version: "3"
services:
    postgres:
        image: "postgres:latest"
        restart: always
        environment:
            POSTGRES_USER: xuanhai
            POSTGRES_PASSWORD: nobodyknow
            POSTGRES_DB: hoctienganh0dong_dev
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - ./db:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432
    nginx:
        restart: always
        depends_on:
            - api
            - client
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "8000:80"
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        depends_on:
          - postgres
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            NODE_ENV: development
            DATABASE_URL: postgres://xuanhai:@postgres:5432/nobodyknow
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        logging:
            driver: none
        volumes:
            - /app/node_modules
            - ./frontend:/app
