apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    component: web
spec:
  containers:
    - name: frontend
      image: xuanhai/muti-client
      ports:
        - containerPort: 8000